login registration leaderboard empty classes
CSC207-2022F-UofT/course-project-group-93 pull request #29
Opened 2022-11-12 22:45 UTC by arifamansoor

All the empty classes without any implementation. *The test for the user entity will not work as user needs to be implemented.

2022-11-12 23:05 UTC, FFFiend approved these changes
Looks good for the file structure of the login-leaderboard

2022-11-12 23:15 UTC, tseamuscorlett requested changes
As I commented in the Discord - no need to push the AssetSetter class.
You can commit & push without selecting that class, or just correct it as follows:

The change was MapHazards -> MazeHazards 
But you changed AssetSetter -> MazeHazards

2022-11-12 23:24 UTC, tseamuscorlett approved these changes

2022-11-12 23:41 UTC, enerko requested changes
You should be good to go if you just fix the javadoc!

2022-11-12 23:41 UTC, enerko commented on src/main/java/adapters/login_leaderboard/LeaderboardPresenter.java
> +    // Transforms the information from all three leaderboards into a viewable format.
Javadoc should be written before the class, in the format of /** **/

2022-11-12 23:47 UTC, enerko commented on src/main/java/adapters/login_leaderboard/LeaderboardPresenter.java
> +    // Transforms the information from all three leaderboards into a viewable format.
Also just a side note: commit messages shouldn't be repeated, as it becomes difficult for others to see what you changed in the commit. It doesn't have to be long, just make sure that the commit message describes what you changed from next time!

2022-11-13 00:00 UTC, tseamuscorlett approved these changes

2022-11-13 00:02 UTC, merged